export const PERSONAL_CHAT = '/PersonalChat'
export const GROUP_CHAT = '/GroupChat'
// export const FRIENDS = '/Friends'
export const LOGIN_PAGE = '/login'
export const REGISTER_PAGE = '/register'
export const PROFILE_PAGE = '/profile'